import 'package:json_annotation/json_annotation.dart';

/// Helper that parses an integer value returned as a string.
int parseIntFromString(dynamic value) =>
    int.tryParse(value?.toString() ?? '') ?? 0;

/// Converter that accepts both integer and string values as an ID.
///
/// The Mastodon API generally returns IDs as strings, but in some cases
/// such as ScheduledStatus params stored in a jsonb column, IDs may be
/// returned as integers. This converter normalizes either format to `String?`.
String? flexibleIdFromJson(dynamic value) => value?.toString();

/// [JsonConverter] that uses [DateTime.tryParse].
///
/// Unlike `DateTime.parse` generated by json_serializable, which throws
/// on invalid formats, this converter falls back to `null` like the
/// legacy implementation.
class SafeDateTimeConverter implements JsonConverter<DateTime?, String?> {
  const SafeDateTimeConverter();

  @override
  DateTime? fromJson(String? json) =>
      json == null ? null : DateTime.tryParse(json);

  @override
  String? toJson(DateTime? object) => object?.toIso8601String();
}
