import 'package:freezed_annotation/freezed_annotation.dart';

part 'mastodon_async_refresh.freezed.dart';
part 'mastodon_async_refresh.g.dart';

/// Status of an asynchronous refresh operation (experimental).
///
/// Corresponds to the response from `GET /api/v1_alpha/async_refreshes/:id`.
@freezed
@JsonSerializable(fieldRename: FieldRename.snake)
class MastodonAsyncRefresh with _$MastodonAsyncRefresh {
  const MastodonAsyncRefresh({
    required this.id,
    required this.status,
    this.resultCount,
  });

  factory MastodonAsyncRefresh.fromJson(Map<String, dynamic> json) =>
      _$MastodonAsyncRefreshFromJson(json);

  /// Serializes to JSON.
  Map<String, dynamic> toJson() => _$MastodonAsyncRefreshToJson(this);

  /// Identifier of the asynchronous refresh.
  @override
  final String id;

  /// Status. Either `running` (in progress) or `finished` (completed).
  @override
  final String status;

  /// Number of results fetched or generated by this operation.
  @override
  final int? resultCount;
}
