import 'dart:async';
import 'dart:io';

import 'package:dio/dio.dart';
import 'package:dio/io.dart';
import 'package:mastodon_client/mastodon_client.dart';
import 'package:web_socket_channel/io.dart';
import 'package:web_socket_channel/web_socket_channel.dart';

/// Connection settings for the local closed-federation E2E environment
/// (`fediverse_e2e`).
///
/// Tests are enabled only when the environment variable `RUN_E2E=1` is set
/// and the `.env.e2e` file generated by `fediverse_e2e/scripts/seed.sh`
/// exists. Otherwise [tryLoad] returns `null` and E2E tests are skipped.
class E2eEnv {
  E2eEnv._({
    required this.mastodonBaseUrl,
    required this.mastodonAdminToken,
    required this.mastodonUserToken,
    required this.misskeyBaseUrl,
    required this.rootCaPath,
    this.fedibirdBaseUrl,
    this.fedibirdAdminToken,
    this.fedibirdUserToken,
  });

  /// Skip reason shown when the E2E environment is not available.
  static const skipReason =
      'E2E environment not available (set RUN_E2E=1 and run '
      'fediverse_e2e: make init)';

  /// Skip reason shown when Fedibird is not part of the running environment.
  static const fedibirdSkipReason =
      'fedibird.test is not seeded (run fediverse_e2e: make build-fedibird '
      '&& make init)';

  final String mastodonBaseUrl;
  final String mastodonAdminToken;
  final String mastodonUserToken;
  final String misskeyBaseUrl;

  /// Path to the self-signed root CA that the E2E servers use.
  final String rootCaPath;

  /// Fedibird settings, `null` when Fedibird is not part of the environment.
  final String? fedibirdBaseUrl;
  final String? fedibirdAdminToken;
  final String? fedibirdUserToken;

  /// Whether Fedibird is available in the running environment.
  ///
  /// Admin token included: [createFedibirdClient] can be asked for an
  /// admin-scoped client, and a missing token there would surface as an
  /// opaque 401 instead of a skip.
  bool get hasFedibird =>
      (fedibirdBaseUrl?.isNotEmpty ?? false) &&
      (fedibirdUserToken?.isNotEmpty ?? false) &&
      (fedibirdAdminToken?.isNotEmpty ?? false);

  /// Loads the E2E environment, or returns `null` when unavailable.
  static E2eEnv? tryLoad() {
    if (Platform.environment['RUN_E2E'] != '1') return null;

    final envPath =
        Platform.environment['E2E_ENV_FILE'] ?? '../fediverse_e2e/.env.e2e';
    final file = File(envPath);
    if (!file.existsSync()) return null;

    final map = <String, String>{};
    for (final line in file.readAsLinesSync()) {
      final trimmed = line.trim();
      if (trimmed.isEmpty || trimmed.startsWith('#')) continue;
      final index = trimmed.indexOf('=');
      if (index <= 0) continue;
      map[trimmed.substring(0, index)] = trimmed.substring(index + 1);
    }

    // rootCAのパスはホスト絶対パスで書かれているため、
    // 存在しない場合(コンテナ内実行など)は .env.e2e からの相対で解決する
    var caPath = map['E2E_ROOT_CA'] ?? '';
    if (caPath.isEmpty || !File(caPath).existsSync()) {
      caPath = '${file.parent.path}/certs/rootCA.crt';
    }
    if (!File(caPath).existsSync()) return null;

    final mastodonBaseUrl = map['MASTODON_BASE_URL'];
    final mastodonAdminToken = map['MASTODON_ADMIN_TOKEN'];
    final mastodonUserToken = map['MASTODON_USER_TOKEN'];
    final misskeyBaseUrl = map['MISSKEY_BASE_URL'];
    if (mastodonBaseUrl == null ||
        mastodonAdminToken == null ||
        mastodonUserToken == null ||
        misskeyBaseUrl == null) {
      return null;
    }

    return E2eEnv._(
      mastodonBaseUrl: mastodonBaseUrl,
      mastodonAdminToken: mastodonAdminToken,
      mastodonUserToken: mastodonUserToken,
      misskeyBaseUrl: misskeyBaseUrl,
      rootCaPath: caPath,
      fedibirdBaseUrl: map['FEDIBIRD_BASE_URL'],
      fedibirdAdminToken: map['FEDIBIRD_ADMIN_TOKEN'],
      fedibirdUserToken: map['FEDIBIRD_USER_TOKEN'],
    );
  }

  /// Creates a dio adapter that trusts the E2E root CA.
  HttpClientAdapter createHttpClientAdapter() => IOHttpClientAdapter(
    createHttpClient: () {
      final context = SecurityContext(withTrustedRoots: true)
        ..setTrustedCertificates(rootCaPath);
      return HttpClient(context: context);
    },
  );

  /// Creates a [MastodonClient] connected to `mastodon.test`.
  ///
  /// Uses the admin token when [admin] is `true`, the regular user token
  /// otherwise.
  MastodonClient createMastodonClient({bool admin = false}) => MastodonClient(
    baseUrl: mastodonBaseUrl,
    accessToken: admin ? mastodonAdminToken : mastodonUserToken,
    httpClientAdapter: createHttpClientAdapter(),
  );

  /// Creates a [MastodonClient] connected to `fedibird.test`.
  ///
  /// Fedibird is a Mastodon 3.4 fork, so the same client is used; call
  /// only when [hasFedibird] is `true`.
  MastodonClient createFedibirdClient({bool admin = false}) => MastodonClient(
    baseUrl: fedibirdBaseUrl!,
    accessToken: admin ? fedibirdAdminToken : fedibirdUserToken,
    httpClientAdapter: createHttpClientAdapter(),
  );

  /// Creates a [MastodonStreaming] connected to `mastodon.test`.
  ///
  /// The default connector cannot complete the TLS handshake against the
  /// self-signed E2E certificate, so a connector trusting [rootCaPath] is
  /// injected instead.
  MastodonStreaming createMastodonStreaming({
    bool admin = false,
    MastodonStreamingConfig? config,
  }) => MastodonStreaming.withConnector(
    baseUrl: mastodonBaseUrl,
    accessToken: admin ? mastodonAdminToken : mastodonUserToken,
    connector: _E2eWebSocketConnector(rootCaPath),
    config: config,
  );
}

/// A [WebSocketConnector] that trusts the E2E root CA.
final class _E2eWebSocketConnector implements WebSocketConnector {
  _E2eWebSocketConnector(this._rootCaPath);

  final String _rootCaPath;

  @override
  Future<WebSocketConnection> connect(WebSocketConnectOptions options) async {
    final context = SecurityContext(withTrustedRoots: true)
      ..setTrustedCertificates(_rootCaPath);
    final channel = IOWebSocketChannel.connect(
      options.uri,
      protocols: options.protocols.isEmpty ? null : options.protocols,
      headers: options.headers.isEmpty ? null : options.headers,
      pingInterval: options.pingInterval,
      connectTimeout: options.connectTimeout,
      customClient: HttpClient(context: context),
    );
    try {
      await channel.ready;
      return _E2eWebSocketConnection(channel);
    } on Object catch (error) {
      try {
        await channel.sink.close();
      } on Object {
        // 接続失敗の原因を close 側の例外で上書きしない。
      }
      throw WebSocketConnectorException(
        message: 'WebSocket handshake failed',
        statusCode: switch (error) {
          WebSocketChannelException(inner: final WebSocketException inner) =>
            inner.httpStatusCode,
          WebSocketException(:final httpStatusCode) => httpStatusCode,
          _ => null,
        },
        cause: error,
      );
    }
  }
}

final class _E2eWebSocketConnection implements WebSocketConnection {
  _E2eWebSocketConnection(this._channel);

  final IOWebSocketChannel _channel;

  @override
  Stream<Object?> get messages => _channel.stream;

  @override
  int? get closeCode => _channel.closeCode;

  @override
  String? get closeReason => _channel.closeReason;

  @override
  void sendText(String data) => _channel.sink.add(data);

  @override
  Future<void> close([int? closeCode, String? closeReason]) =>
      _channel.sink.close(closeCode, closeReason);
}

/// Polls [probe] until it returns non-null, or fails after [timeout].
///
/// 連合配送は非同期のため、到達確認は必ずこれで待つこと。
Future<T> pollUntil<T>(
  Future<T?> Function() probe, {
  Duration timeout = const Duration(seconds: 90),
  Duration interval = const Duration(seconds: 2),
}) async {
  final deadline = DateTime.now().add(timeout);
  Object? lastError;
  while (DateTime.now().isBefore(deadline)) {
    try {
      final result = await probe();
      if (result != null) return result;
    } on Exception catch (e) {
      lastError = e;
    }
    await Future<void>.delayed(interval);
  }
  throw TimeoutException(
    'pollUntil timed out (last error: $lastError)',
    timeout,
  );
}
